export enum RoleEnum {
  STUDENT = "STUDENT",
  TEACHER = "TEACHER",
  ADMINISTRATOR = "ADMINISTRATOR",
  GENERAL_SERVICES_STAFF = "GENERAL_SERVICES_STAFF",
  MEDICAL_STAFF = "MEDICAL_STAFF",
  MEDICAL_SECRETARY = "MEDICAL_SECRETARY",
}
