export enum Role {
  ADMINISTRATOR = "ADMINISTRATOR",
  MEDICAL_SECRETARY = "MEDICAL_SECRETARY",
  MEDICAL_STAFF = "MEDICAL_STAFF",
  GENERAL_SERVICES_STAFF = "GENERAL_SERVICES_STAFF",
  PREFECT = "PREFECT",
  STUDENT = "STUDENT",
  TRAINER = "TRAINER",
  WELLNESS_STAFF = "WELLNESS_STAFF",
  MONITOR = "MONITOR",
  TEACHER = "TEACHER",
}
